### ISSUE TITLE
Include journald in compilation path to log to systemd journal

### ISSUE THREAD

**Issue by willzhang** [mgoltzsche/podman-static#57]
podman-static 4.4.3 error
```
root@node01:~# cephadm bootstrap --mon-ip 192.168.72.40
Verifying podman|docker is present...
Verifying lvm2 is present...
Verifying time synchronization is in place...
Unit chrony.service is enabled and running
Repeating the final host check...
podman (/usr/local/bin/podman) version 4.4.3 is present
systemctl is present
lvcreate is present
Unit chrony.service is enabled and running
Host looks OK
Cluster fsid: fd0ccf44-d176-11ed-bad6-d1da98c13f11
Verifying IP 192.168.72.40 port 3300 ...
Verifying IP 192.168.72.40 port 6789 ...
Mon IP `192.168.72.40` is in CIDR network `192.168.72.0/24`
Mon IP `192.168.72.40` is in CIDR network `192.168.72.0/24`
Internal network (--cluster-network) has not been provided, OSD replication will default to the public_network
Pulling container image quay.io/ceph/ceph:v17...
Ceph version: ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)
Extracting ceph user uid/gid from container image...
Creating initial keys...
Creating initial monmap...
Creating mon...
Non-zero exit code 1 from systemctl start ceph-fd0ccf44-d176-11ed-bad6-d1da98c13f11@mon.node01
systemctl: stderr Job for ceph-fd0ccf44-d176-11ed-bad6-d1da98c13f11@mon.node01.service failed because the control process exited with error code.
systemctl: stderr See "systemctl status ceph-fd0ccf44-d176-11ed-bad6-d1da98c13f11@mon.node01.service" and "journalctl -xeu ceph-fd0ccf44-d176-11ed-bad6-d1da98c13f11@mon.node01.service" for details.
Traceback (most recent call last):
  File "/usr/local/bin/cephadm", line 9653, in <module>
    main()
  File "/usr/local/bin/cephadm", line 9641, in main
    r = ctx.func(ctx)
  File "/usr/local/bin/cephadm", line 2205, in _default_image
    return func(ctx)
  File "/usr/local/bin/cephadm", line 5692, in command_bootstrap
    create_mon(ctx, uid, gid, fsid, mon_id)
  File "/usr/local/bin/cephadm", line 5146, in create_mon
    deploy_daemon(ctx, fsid, 'mon', mon_id, mon_c, uid, gid,
  File "/usr/local/bin/cephadm", line 3317, in deploy_daemon
    deploy_daemon_units(ctx, fsid, uid, gid, daemon_type, daemon_id,
  File "/usr/local/bin/cephadm", line 3573, in deploy_daemon_units
    call_throws(ctx, ['systemctl', 'start', unit_name])
  File "/usr/local/bin/cephadm", line 1852, in call_throws
    raise RuntimeError(f'Failed command: {" ".join(command)}: {s}')
RuntimeError: Failed command: systemctl start ceph-fd0ccf44-d176-11ed-bad6-d1da98c13f11@mon.node01: Job for ceph-fd0ccf44-d176-11ed-bad6-d1da98c13f11@mon.node01.service failed because the control process exited with error code.
See "systemctl status ceph-fd0ccf44-d176-11ed-bad6-d1da98c13f11@mon.node01.service" and "journalctl -xeu ceph-fd0ccf44-d176-11ed-bad6-d1da98c13f11@mon.node01.service" for details.
```

```
root@node01:~# /bin/bash /var/lib/ceph/4162dd60-d176-11ed-bad6-d1da98c13f11/mon.node01/unit.run 
[conmon:e] Include journald in compilation path to log to systemd journal
Error: exit status 1
root@node01:~# 
```

```
root@node01:~# podman run --name test --log-driver journald -d alpine sleep 1000
[conmon:e] Include journald in compilation path to log to systemd journal
Error: write child: broken pipe
root@node01:~# 
```

```
root@node01:~# podman info --debug
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /usr/local/lib/podman/conmon
    version: 'conmon version 2.1.7, commit: f633919178f6c8ee4fb41b848a056ec33f8d707d'
  cpuUtilization:
    idlePercent: 97.58
    systemPercent: 0.76
    userPercent: 1.66
  cpus: 4
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: file
  hostname: node01
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.0-27-generic
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 4623376384
  memTotal: 8337428480
  networkBackend: cni
  ociRuntime:
    name: runc
    package: Unknown
    path: /usr/local/bin/runc
    version: |-
      runc version 1.1.4
      commit: v1.1.4-0-g5fd4c4d
      spec: 1.0.2-dev
      go: go1.18.10
      libseccomp: 2.5.4
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/local/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 4115656704
  swapTotal: 4115656704
  uptime: 0h 28m 50.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.ignore_chown_errors: "true"
    overlay.mount_program:
      Executable: /usr/local/bin/fuse-overlayfs
      Package: Unknown
      Version: |-
        fuse-overlayfs: version 1.10
        fusermount3 version: 3.10.5
        FUSE library version 3.14.0
        using FUSE kernel interface version 7.38
    overlay.mountopt: nodev,fsync=0
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 105223553024
  graphRootUsed: 9119862784
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 3
  runRoot: /var/run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.4.3
  Built: 0
  BuiltTime: Thu Jan  1 08:00:00 1970
  GitCommit: ""
  GoVersion: go1.18.10
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.3
```

releated: https://github.com/containers/podman/issues/9481

**Comment by mgoltzsche** [comment]
The binaries shipped by this repo are built on alpine that uses musl libc instead of glibc. systemd/journald cannot be built on alpine since it relies on glibc. Also, statically linking the podman binary with systemd/journald would significantly increase the binary's size.
I suggest not to use the podman option `--log-driver=journald`.
